# Generated by Django 5.0.2 on 2024-03-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('groupe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('classeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_note_ANDY_SS.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('classeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_note_ANDY_SS.classe')),
                ('profID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_note_ANDY_SS.prof')),
            ],
        ),
        migrations.CreateModel(
            name='note_etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('etudiantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_note_ANDY_SS.etudiant')),
                ('matiereID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_note_ANDY_SS.matiere')),
            ],
        ),
    ]
