# Generated by Django 5.0.2 on 2024-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_note_ANDY_SS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='mdp',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='prof',
            name='mdp',
            field=models.CharField(default='mdp123', max_length=100),
        ),
    ]
