# Generated by Django 5.0.2 on 2024-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_note_ANDY_SS', '0002_etudiant_mdp_prof_mdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_etudiant',
            name='note',
            field=models.IntegerField(default=0),
        ),
    ]
